del /S *.ncb
del /S *.obj
del /S *.pdb
del /S *.pch
del /S *.exp
del /S /A:H *.suo
del /S *.plg
del /S *.dep
del /S *.ilk
del /S *.idb
del /S *.sdf
del /S *.ipch
del /S *.exe
del /S *.tlog
del /S *.log
rd  /s/q debug
rd  /s/q ipch
del /S *.lastbuildstate
del /S *.user